############# waypoint_id -> waypoint_id
uint16 waypoint_id

############# crossover_work_traffic_lights -> tlr
TrafficLightResultCustom tlr

#############
uint8 start

############# connection_check -> connection_check
uint8 connection_check

############# goal -> goal
uint8 goal

############# point_move -> point_move
uint8 point_move

############# route_correction -> route_correction
float32 route_correction

############# stop_point -> waiting_state
uint8 waiting_state

############# detection_range_front_L -> det_rng_fl
float32 det_rng_fl

############# detection_range_front_R -> det_rng_fr
float32 det_rng_fr

############# detection_range_rear_L -> det_rng_rl
float32 det_rng_rl

############# detection_range_rear_R -> det_rng_rr
float32 det_rng_rr

############# cargo_left -> cargo_left
float32 cargo_left

############# cargo_right -> cargo_right
float32 cargo_right

############# fatal_area_left -> fatal_area_left
float32 fatal_area_left

############# fatal_area_right -> fatal_area_right
float32 fatal_area_right

############# obstacle_detection_distance_change -> sdo
float32 sdo

############# winker_point -> winker_point
uint8 winker_point

############# obstacle_sensor_range -> osr
uint8 osr

############# mode_change -> mode_change
uint8 mode_change

############# attention_broadcast -> attention_broadcast
uint8 attention_broadcast

############# inter_vehicular_distance -> ivd
float32 ivd

############# minimum_target_point_distance -> min_tpd
float32 min_tpd

############# target_point_ratio -> target_point_ratio
float32 target_point_ratio

############# voxel_leaf_size -> voxel_leaf_size
float32 voxel_leaf_size

############# local_max_slope -> local_max_slope
float64  local_max_slope

############# preliminary_output -> preliminary_output
uint8 preliminary_output

############# route_change -> route_change
uint8 route_change

############# start_trigger -> start_trigger
uint8 start_trigger

############# pause_point -> pause_point
uint8 pause_point

############# pause_time -> pause_time
float32 pause_time

############# cross_point -> cross_point
uint8 cross_point

############
uint8 shutter_point

############
uint8 shutter_stop

############
uint8 shutter_passed

############
uint8 traffic_light_flg

############
uint8 lamp_id

############
uint8 object_detection_intersect

############# cross_point_detection_area_left -> cross_point_detection_area_left
float32 cross_point_detection_area_left

############# cross_point_detection_area_right -> cross_point_detection_area_right
float32 cross_point_detection_area_right

############# cross_point_detection_area_front -> cross_point_detection_area_front
float32 cross_point_detection_area_front

############# cross_point_detection_area_back -> cross_point_detection_area_back
float32 cross_point_detection_area_back

############# battery_low -> battery_low
uint8 battery_low

############# battery_low_threshold -> battery_low_threshold
uint8 battery_low_threshold

############# battery_exchange -> battery_exchange
uint8 battery_exchange

############# battery_exchange_threshold -> battery_exchange_threshold
uint8 battery_exchange_threshold

############# vehicle_waypoint_distance -> vehicle_waypoint_distance
float32 vehicle_waypoint_distance
