MicroStrain 3DM-GX5-15:
  baud: '115200'
  frequency: '100'
  port: /dev/ttyACM0
PointGrey LadyBug 5:
  CalibrationFile: ''
  SCALE: 0.2
Velodyne VLP-16:
  calibration: ''
approximate_ndt_mapping:
  imu_topic: !!python/unicode '/imu_raw'
  imu_upside_down: false
  leaf_size: 1.0
  max_iterations: 30
  max_scan_range: 60.0
  max_submap_size: 20.0
  min_add_scan_shift: 5.0
  min_scan_range: 2.0
  resolution: 1.0
  step_size: 0.1
  trans_epsilon: 0.01
  use_imu: false
  use_odom: false
  use_openmp: false
astar_avoid:
  avoid_start_velocity: 3.0
  avoid_waypoints_velocity: 10.0
  costmap_topic: semantics/costmap_generator/occupancy_grid
  enable_avoidance: false
  replan_interval: 2.0
astar_navi:
  costmap_topic: semantics/costmap_generator/occupancy_grid
  update_rate: 0.5
  use_back: false
  waypoints_velocity: 5.0
booted_cmds:
  names: []
calibration_publisher:
  camera_frame: camera
  camera_id: ''
  camera_info_topic: /camera_info
  file: ''
  image_topic_src: /image_raw
  projection_matrix_topic: /projection_matrix
  publish_camera_info: true
  publish_extrinsic_mat: true
  register_lidar2camera_tf: true
  target_frame: velodyne
car_dpm:
  Lambda: 10
  group_threshold: 0.1
  num_bins: 9
  num_cells: 8
  score_threshold: -0.5
car_fusion:
  car: true
  dispersion: 1.0
  max_height: 2.0
  max_low_height: -1.0
  min_low_height: -1.5
  min_points: 2
  pedestrian: false
  sync: false
car_kf:
  camera_id: ''
  carHEAD: true
  default_lifespan: 8
  error_estimate_covariance: 1000000.0
  initial_lifespan: 4
  measurement_noise_covariance: 25.0
  noise_covariance: 1.0
  orb_features: 2000
  pedestrian: false
  percentage_of_overlapping: 0.0
  sync: false
  use_orb: 0
cloud_transformer:
  input_point_topic: /points_raw
  output_point_topic: /points_transformed
  target_frame: base_link
compare_map_filter:
  distance_threshold: 0.2
  input_map_topic: /points_map
  input_point_topic: !!python/unicode '/points_raw'
  max_clipping_height: 0.7
  min_clipping_height: 1.0
  output_match_topic: /points_ground
  output_unmatch_topic: /points_no_ground
decision_maker(experimental):
  auto_engage: true
  auto_mission_change: false
  auto_mission_reload: true
  baselink_tf: base_link
  change_threshold_angle: 15.0
  change_threshold_dist: 1.0
  disuse_vector_map: true
  goal_threshold_dist: 3.0
  goal_threshold_vel: 0.1
  num_of_steer_behind: 20
  points_topic: /points_lanes
  use_fms: false
detection_qs:
  file: ''
distance_filter:
  measurement_range: 200
  points_topic: !!python/unicode '/points_raw'
  sample_num: 10000
  sync: false
icp_matching:
  error_threshold: 1.0
  euclidean_fitness_epsilon: 0.1
  init_pos_gnss: 1
  max_correspondence_distance: 1.0
  maximum_iterations: 100
  pitch: 0.0
  ransac_outlier_rejection_threshold: 1.0
  roll: 0.0
  sync: false
  transformation_epsilon: 0.01
  use_predict_pose: 1
  x: 0.0
  y: 0.0
  yaw: 0.0
  z: 0.0
lane_navi:
  output_file: /tmp/lane_waypoint.csv
  velocity: 40.0
lane_rule:
  acceleration: 1.0
  number_of_smoothing_count: 0
  number_of_zeros_ahead: 0
  number_of_zeros_behind: 0
  stopline_search_radius: 1.0
lane_select:
  distance_threshold_neighbor_lanes: 5.0
  lane_change_interval: 10.0
  lane_change_target_minimum: 10.0
  lane_change_target_ratio: 5.0
  vector_length_hermite_curve: 10.0
lane_stop:
  traffic_light: 1
lidar_euclidean_cluster_detect:
  clip_max_height: 0.5
  clip_min_height: -1
  cluster_merge_threshold: 1.5
  cluster_size_max: 100000
  cluster_size_min: 20
  clustering_distance: 0.75
  clustering_distances: '[0.5,1.1,1.6,2.1,2.6]'
  clustering_ranges: '[15,30,45,60]'
  downsample_cloud: false
  keep_lane_left_distance: 5.0
  keep_lane_right_distance: 5.0
  keep_lanes: true
  leaf_size: 0.6
  output_frame: velodyne
  points_node: !!python/unicode '/points_no_ground'
  pose_estimation: false
  publish_filtered: false
  remove_ground: true
  remove_points_upto: 0.0
  sync: false
  use_diffnormals: false
  use_gpu: true
  use_multiple_thres: false
  use_vector_map: false
  vectormap_frame: map
  wayarea_gridmap_layer: wayarea
  wayarea_gridmap_topic: !!python/unicode 'grid_map_wayarea'
  wayarea_no_road_value: 255
localization_qs:
  file: ''
map_qs:
  file: ''
mission_planning_qs:
  file: ''
motion_planning_qs:
  file: ''
multi_lidar_calibrator:
  ndt_epsilon: 0.01
  ndt_iterations: 400
  ndt_resolution: 1.0
  ndt_step_size: 0.1
  pitch: 0.0
  points_child_src: !!python/unicode '/vlp16_1/velodyne_points'
  points_parent_src: !!python/unicode '/vlp16_0/velodyne_points'
  roll: 0.0
  voxel_size: 0.5
  x: 0.0
  y: 0.0
  yaw: 0.0
  z: 0.0
ndt_mapping:
  imu_topic: !!python/unicode '/imu_raw'
  imu_upside_down: false
  incremental_voxel_update: false
  leaf_size: 1.0
  max_iterations: 30
  max_scan_range: 120.0
  method_type: 0
  min_add_scan_shift: 2.0
  min_scan_range: 2.0
  resolution: 1.0
  step_size: 0.1
  trans_epsilon: 0.01
  use_imu: false
  use_odom: false
ndt_matching:
  error_threshold: 1.0
  get_height: true
  imu_topic: !!python/unicode '/imu_raw'
  imu_upside_down: false
  init_pos_gnss: 0
  max_iterations: 30
  method_type: 0
  output_log_data: true
  pitch: 0.0
  resolution: 1.0
  roll: 0.0
  step_size: 0.1
  sync: false
  trans_epsilon: 0.01
  use_imu: false
  use_odom: false
  use_predict_pose: 1
  x: 0.0
  y: 0.0
  yaw: 0.0
  z: 0.0
ndt_matching_monitor:
  fatal_time_threshold: 2.0
  iteration_threshold_stop: 32
  iteration_threshold_warn: 10
  min_stable_samples: 30
  score_threshold_delta: 14.0
pcd_binarizer:
  path_pcd_binarizer: ''
  point_type: !!python/unicode 'PointXYZ'
pcd_filter:
  leaf_size: 0.5
  path_pcd_filter: /home/nvidia/Autoware/tmp/bin_autoware-210923.pcd
  point_type: !!python/unicode 'PointXYZ'
pedestrian_dpm:
  Lambda: 10
  group_threshold: 0.3
  num_bins: 9
  num_cells: 8
  score_threshold: 0.6
pedestrian_fusion:
  dispersion: 1.0
  max_height: 2.0
  max_low_height: -1.0
  min_low_height: -1.5
  min_points: 2
pedestrian_kf:
  default_lifespan: 8
  error_estimate_covariance: 1000000.0
  initial_lifespan: 4
  measurement_noise_covariance: 25.0
  noise_covariance: 1.0
  orb_features: 2000
  percentage_of_overlapping: 0.0
  use_orb: 0
play_rosbag_play:
  file: ''
  rate: ''
  repeat: false
  start: 0
point_cloud:
  path_area_list: None
  path_area_list_cmd_param: null
  path_pcd: /home/nvidia/Autoware/BACK_UP/01_MAP/autoware-220127.pcd
  scene_num: noupdate
points_concat_filter:
  input_topics: '[/livox/lidar_1HDDGC500101131,/livox/lidar_1HDDGC500101891,/points_raw]'
  output_frame_id: velodyne
  output_topic: /points_raw2
points_image:
  camera_id: ''
  sync: false
pure_pursuit:
  displacement_threshold: 0.0
  is_linear_interpolation: true
  lookahead_distance: 4.0
  lookahead_ratio: 1.75
  minimum_lookahead_distance: 1.75
  param_flag: 0
  publishes_for_steering_robot: false
  relative_angle_threshold: 0
  velocity: 5.0
random_filter:
  measurement_range: 200
  points_topic: !!python/unicode '/points_raw'
  sample_num: 10000
  sync: false
ray_ground_filter:
  clipping_height: 0.5
  concentric_divider_distance: 0.01
  general_max_slope: 10
  input_point_topic: !!python/unicode '/points_raw'
  local_max_slope: 25
  min_height_threshold: 0.05
  min_point_distance: 3.0
  radial_divider_angle: 1.0
  reclass_distance_threshold: 0.2
  sensor_height: 2.3
ring_filter:
  measurement_range: 200
  points_topic: !!python/unicode '/points_raw'
  ring_div: 3
  sync: false
  voxel_leaf_size: 2.0
ring_ground_filter:
  max_slope: 10.00
  point_topic: !!python/unicode '/points_raw'
  sensor_height: 1.85
  sensor_model: !!python/unicode '16'
  vertical_thres: 0.08
sensing_qs:
  file: ''
setup_tf:
  frame_id: /base_link
  localizer_cmd_param: /velodyne
  localizer_rosparam: velodyne
  period_in_ms: 10
  pitch: 0.0
  roll: 0.0
  x: 0.345
  y: 0.0
  yaw: 0.0
  z: 1.865
tf:
  file: ''
twist_filter:
  lateral_accel_limit: 0.8
  lowpass_gain_angular_z: 0.0
  lowpass_gain_linear_x: 0.0
vector_map:
  path_vec: ''
vehicle_info:
  info_path: ''
vehicle_model:
  model_path: ''
vel_pose_connect:
  sim_mode: false
  topic_pose_stamped: !!python/unicode '/ndt_pose'
  topic_twist_stamped: /estimate_twist
velocity_set:
  deceleration_obstacle: 0.7
  deceleration_range: 0
  deceleration_stopline: 0.3
  detection_height_bottom: -2.0
  detection_height_top: 0.0
  detection_range: 0.0
  enable_multiple_crosswalk_detection: false
  points_topic: points_no_ground
  stop_distance_obstacle: 5.0
  stop_distance_stopline: 3.0
  temporal_waypoints_size: 150.0
  threshold_points: 3
  use_crosswalk_detection: false
  velocity_change_limit: 7.0
virtual_scan_image:
  camera_id: ''
  sync: false
vision_beyond_track:
  budget: 20
  camera_height: 1.2
  camera_info_src: /camera_info
  cpu_chks:
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  nice: 0
  objects_topic_src: /detection/vision_objects
  period: 100
  policy: !!python/unicode 'FIFO'
  prio: 99
  real_time: false
vision_darknet_yolo2:
  camera_id: !!python/unicode ''
  gpu_device_id: 0
  image_src: !!python/unicode '/image_raw'
  names_file: /home/nvidia/Autoware/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/cfg/coco.names
  network_definition_file: /home/nvidia/Autoware/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/cfg/yolov2.cfg
  nms_threshold: 0.45
  pretrained_model_file: /home/nvidia/Autoware/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/data/yolov3.weights
  score_threshold: 0.5
vision_darknet_yolo3:
  camera_id: !!python/unicode ''
  gpu_device_id: 0
  image_src: !!python/unicode '/camera/color/image_raw'
  names_file: /home/nvidia/Autoware/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/cfg/coco.names
  network_definition_file: /home/nvidia/Autoware/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/cfg/yolov3.cfg
  nms_threshold: 0.45
  pretrained_model_file: /home/nvidia/Autoware/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/data/yolov3.weights
  score_threshold: 0.5
vision_dpm_ttic_detect:
  camera_id: ''
  car: true
  comp_model_car: $(rospack find vision_dpm_ttic_detect)/data/car_comp.csv
  comp_model_pedestrian: $(rospack find vision_dpm_ttic_detect)/data/person_comp.csv
  part_model_car: $(rospack find vision_dpm_ttic_detect)/data/car_part.csv
  part_model_pedestrian: $(rospack find vision_dpm_ttic_detect)/data/person_part.csv
  pedestrian: false
  root_model_car: $(rospack find vision_dpm_ttic_detect)/data/car_root.csv
  root_model_pedestrian: $(rospack find vision_dpm_ttic_detect)/data/person_root.csv
  sync: false
  use_gpu: 'False'
vision_ssd_detect:
  camera_id: !!python/unicode ''
  gpu_device_id: 0
  image_src: /image_raw
  network_definition_file: ~/ssdcaffe/models/VGGNet/VOC0712Plus/SSD_300x300/deploy.prototxt
  pretrained_model_file: ~/ssdcaffe/models/VGGNet/VOC0712Plus/SSD_300x300/VGG_VOC0712Plus_SSD_300x300_iter_240000.caffemodel
  score_threshold: 0.6
  use_gpu: true
voxel_grid_filter:
  measurement_range: 100
  points_topic: !!python/unicode '/points_raw'
  sync: false
  voxel_leaf_size: 2.0
waypoint_clicker:
  output_file: /home/nvidia/Autoware/zip_file/RUN_DATA/1TS_01/ROUTE_FILES/Hiroba/0224/kyokusen.csv
  velocity: 40.0
waypoint_loader:
  accel_limit: 0.5
  braking_distance: 5
  decel_limit: 0.3
  end_point_offset: 1
  load_csv: true
  multi_lane_csv: /home/nvidia/Autoware_1.15.04/BACK_UP/02_ROUTE/dabwitso trial folder/route1.csv
  overwrite_vmax_mode: false
  radius_min: 6.0
  radius_thresh: 20.0
  realtime_tuning_mode: false
  replan_curve_mode: false
  replan_endpoint_mode: true
  replanning_mode: false
  resample_interval: 1.0
  resample_mode: true
  velocity_max: 20.0
  velocity_min: 4.0
  velocity_offset: 4
waypoint_saver:
  budget: 20
  cpu_chks:
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  input_type: 0
  interval: 0.5
  lane_topic: !!python/unicode '/lane_waypoints_array'
  nice: 0
  period: 100
  policy: !!python/unicode 'FIFO'
  prio: 99
  real_time: false
  save_filename: /home/nvidia/Autoware/BACK_UP/02_ROUTE/kafner_2.csv
  save_velocity: true
waypoint_velocity_visualizer:
  plot_metric_interval: 1.0
  use_bar_plot: false
  use_line_plot: true
  use_text_plot: true
wf_simulator:
  accel_rate: 10.0
  angle_error: 0.0
  initialize_source: !!python/unicode 'Rviz'
  position_error: 0.0
